enarx/drawbridge

.github/workflows/lint.yml
.github/workflows/test.yml
crates/core/src/res.rs
src/lib.rs
src/main.rs

feat: add support for namespacing

---

crates/repo/src/lib.rs
crates/tags/src/name.rs

Rely of Axum for routing. This fixes a few issues where e.g. `/:namespace/_tag` route was not properly handled, while also making the implementation simpler for #35

feat(repo): rely on Axum for routing

---

Cargo.lock
crates/repo/src/lib.rs
crates/repo/src/namespace.rs
crates/store/src/lib.rs
crates/tags/Cargo.toml
crates/tags/src/lib.rs
src/main.rs

Fixed a few routing issues along the way
Closes #64 
Refs #67

feat(repo): nest tree service under `_tag`

---

.github/CODEOWNERS

We won't be able to merge PRs quickly otherwise

ci: add @rjzak to CODEOWNERS

---

Cargo.lock
crates/repo/Cargo.toml
crates/repo/src/lib.rs

Closes #66 
Signed-off-by: Richard Zak <richard@profian.com>

feat: repo unit tests

---

crates/app/src/tags.rs
crates/app/tests/helpers/mod.rs
crates/app/tests/helpers/repo.rs
crates/app/tests/helpers/tag.rs
crates/app/tests/helpers/tree.rs
crates/app/tests/mod.rs

This is a (generally) inefficient approach, which is good enough for memory backend.
Closes #94 
Refs #92

feat(tags): check namespace in tag listing endpoint

---

Cargo.lock
Cargo.toml
crates/app/Cargo.toml
crates/byte/Cargo.toml
crates/hash/Cargo.toml
crates/jose/Cargo.toml
crates/store/Cargo.toml
crates/type/Cargo.toml
crates/type/src/meta.rs

Similar to https://github.com/enarx/enarx/pull/1759

build: rely on upstream Axum, remove unused features

---

crates/app/tests/mod.rs

Assert that the server shuts down cleanly

test: assert graceful shutdown

---

Cargo.lock
crates/app/tests/mod.rs
flake.lock
flake.nix

build: update dependencies

---

Cargo.lock
crates/app/src/tags.rs
crates/type/Cargo.toml
crates/type/src/tag/name.rs

feat: enforce SemVer tags

---

Cargo.lock
crates/app/Cargo.toml
crates/app/tests/helpers/tree.rs
crates/app/tests/mod.rs

Follow-up on #107 , which was merged without the review addressed.
@bstrie please avoid merging PRs you're not the author of. If automatic merge on approval is the intention, the author of the PR should enable auto-merge.

refactor: clean-up app tests

---

crates/client/src/entity.rs

refactor(client): remove redundant references

---

Cargo.lock
crates/app/src/store/repo.rs
crates/app/src/store/tree.rs
crates/app/src/tags/put.rs
crates/app/src/trees/put.rs
crates/app/tests/helpers/repo.rs
crates/app/tests/helpers/tag.rs
crates/app/tests/helpers/tree.rs
crates/app/tests/helpers/user.rs
crates/app/tests/mod.rs
crates/client/src/entity.rs
crates/client/src/tag.rs
crates/client/src/tree.rs
crates/type/Cargo.toml
crates/type/src/digest/algorithms.rs
crates/type/src/lib.rs
crates/type/src/tag/entry.rs
crates/type/src/tree/directory.rs
crates/type/src/tree/entry.rs
crates/type/src/tree/mod.rs
crates/type/src/tree/name.rs
crates/type/src/tree/path.rs
tests/mod.rs

feat: create trees and unsigned tags from local FS paths

---

crates/app/src/handle.rs
crates/app/src/lib.rs
rust-toolchain.toml

I saw that people were hitting some ICEs during development. To make it easier to diagnose such ICEs in the future, let's support building on stable.

refactor: remove nightly feature and compile on stable Rust

---

crates/client/src/entity.rs
crates/client/src/lib.rs
tests/mod.rs

feat(client): add `Bearer` token auth support

---

crates/client/src/entity.rs

refactor: address clippy warnings

---

Cargo.lock
Cargo.toml
src/main.rs

feat: parse CLI arguments from config file

---

Cargo.nix

The dependency file became out-of-date once #208 was merged.

build(nix): regenerate dependency file

---

Cargo.toml
crates/app/Cargo.toml

feat: disable trace logs in release builds

---

.gitignore
Drawbridge.toml.example

docs: add example config file

---

flake.nix

https://github.com/profianinc/benefice/pull/33 cleanly applied to this repo via
```
curl -sL https://github.com/profianinc/benefice/pull/33.patch | git am -3
```

build(nix): add debug builds

---

flake.lock
flake.nix

build(nix): update flake lock

---

crates/type/src/tree/mod.rs

Not perfect, but best we can do for now

feat(type): infer media type from extension

---

Cargo.lock
Cargo.nix
crates/byte/src/lib.rs
crates/client/src/entity.rs
crates/client/src/lib.rs
crates/client/src/repo.rs
crates/client/src/tag.rs
crates/client/src/tree.rs
crates/client/src/user.rs
crates/jose/Cargo.toml
crates/jose/src/lib.rs
crates/server/Cargo.toml
crates/server/src/auth/tls.rs
crates/server/src/builder.rs
crates/server/src/handle.rs
crates/server/src/lib.rs
crates/server/src/store/entity.rs
crates/type/Cargo.toml
crates/type/src/digest/algorithm.rs
crates/type/src/digest/algorithms.rs
crates/type/src/digest/digests.rs
crates/type/src/digest/reader.rs
crates/type/src/digest/verifier.rs
crates/type/src/digest/writer.rs
crates/type/src/lib.rs
crates/type/src/meta.rs
crates/type/src/repository/config.rs
crates/type/src/tree/mod.rs
src/lib.rs
src/main.rs

feat: use stricter linting, fix mistakes

---

Cargo.lock
Cargo.nix
Cargo.toml
crates/server/src/store/entity.rs
flake.lock
flake.nix
src/main.rs

Same as https://github.com/profianinc/benefice/pull/158

feat: use `confargs` for argument parsing

---

Cargo.lock
Cargo.nix
Cargo.toml
crates/server/Cargo.toml
crates/server/src/auth/oidc.rs
crates/server/src/builder.rs
crates/server/src/handle.rs
crates/server/src/lib.rs
crates/server/src/repos/get.rs
crates/server/src/repos/head.rs
crates/server/src/repos/put.rs
crates/server/src/store/entity.rs
crates/server/src/store/tag.rs
crates/server/src/tags/get.rs
crates/server/src/tags/head.rs
crates/server/src/tags/put.rs
crates/server/src/tags/query.rs
crates/server/src/trees/get.rs
crates/server/src/trees/head.rs
crates/server/src/trees/put.rs
crates/server/src/users/get.rs
crates/server/src/users/head.rs
crates/server/src/users/put.rs
src/main.rs
tests/mod.rs

This also switches the log crate out for tracing.
Signed-off-by: Patrick Uiterwijk <patrick@puiterwijk.org>

feat: add structured logging for request/response

---

Cargo.lock
Cargo.nix
crates/server/Cargo.toml
crates/server/src/builder.rs

Signed-off-by: Patrick Uiterwijk <patrick@puiterwijk.org>

feat: include request_id in logs

---

crates/server/src/builder.rs

Closes #264
Let me know if I should put this in the `handle` function. Also I'm not sure what the API is so I don't know if `/health` conflicts with any existing endpoints (I don't think it does just checking).

feat: add health check endpoint

---

crates/client/src/repo.rs
crates/type/src/repository/name.rs
crates/type/src/tag/name.rs
crates/type/src/tree/directory.rs
crates/type/src/tree/name.rs
crates/type/src/tree/path.rs
crates/type/src/user/name.rs

- Fix `Deserialize` implementations
- Add #[serde(transparent)] where appropriate

fix(type): implement useful traits, fix serde

---

.github/workflows/lint.yml
.github/workflows/release.yml

ci: configure nix github token

---

Cargo.lock
Cargo.toml
src/main.rs

build: upgrade clap to 4.0.26

---

Cargo.lock
Cargo.toml
crates/byte/Cargo.toml
crates/client/Cargo.toml
crates/jose/Cargo.toml
crates/server/Cargo.toml
crates/server/src/auth/mod.rs
crates/server/src/auth/oidc.rs
crates/type/Cargo.toml
crates/type/src/lib.rs
tests/mod.rs

build: release 0.3.0

---

crates/client/src/lib.rs

Allows a user agent to be set on the drawbridge client, and defaults to the current crate name and version.
Signed-off-by: Patrick Uiterwijk <patrick@puiterwijk.org>

feat: allow specifying user-agent in client

---

Cargo.lock
Cargo.toml
crates/client/Cargo.toml
crates/client/src/tag.rs
crates/type/Cargo.toml
crates/type/src/tree/directory.rs
crates/type/src/tree/mod.rs

feat: allow programmatic construction of trees not tied to a FS path

---

Cargo.lock
Cargo.toml
crates/client/src/lib.rs
crates/server/src/auth/tls.rs
crates/server/src/builder.rs
crates/type/src/digest/digests.rs

Breaking API changes addressed with these dependencies

chore(deps): satisfy clippy, update rustls and ureq
