crates/hash/src/reader.rs
crates/tree/src/meta.rs

Simplify the API by using consistent naming scheme for headers and metadata fields as was suggested in #22 
Add a few tests as well.

refactor: match metadata field names with header names

---

Cargo.lock
Cargo.toml
crates/http/Cargo.toml
crates/name/Cargo.toml
crates/name/src/lib.rs
src/main.rs

Reorganize the crates for better separation of concerns and ability to have one crate (core) with functionality shared between components (e.g. namespacing)

refactor: move `src/lib.rs` into a separate crate

---

Cargo.lock
Cargo.toml
crates/byte/Cargo.toml
crates/byte/src/lib.rs
crates/jose/Cargo.toml
crates/jose/src/b64.rs
crates/jose/src/jws.rs
crates/jose/src/lib.rs
crates/type/Cargo.toml
crates/type/src/digest/algorithm.rs
crates/type/src/digest/algorithms.rs
crates/type/src/digest/digests.rs
crates/type/src/digest/mod.rs
crates/type/src/digest/reader.rs
crates/type/src/digest/verifier.rs
crates/type/src/digest/writer.rs
crates/type/src/lib.rs
crates/type/src/meta.rs

This contains types shared by clients and various server components.
Signed-off-by: Nathaniel McCallum <nathaniel@profian.com>

refactor: add the drawbridge-type crate

---

Cargo.lock
crates/repo/Cargo.toml
crates/repo/src/lib.rs
crates/store/src/lib.rs

Added repo management routes, fixed the path parsing
Refs #35 
@rjzak could you (can be follow-up PR):
1. Extract `Namespace`, related parsing and testing logic to `namespace.rs`?
2. Add tests for routing in `lib.rs`?
3. Add repository existence checking (see https://github.com/profianinc/drawbridge/pull/63/files#r854318531)

feat(repo): add repository management routes

---

crates/app/src/app.rs

This makes sure `/<path>` and `/<path>/` are routed the same way
https://doc.rust-lang.org/std/string/struct.String.html#method.split_terminator

fix(app): trim trailing slashes

---

Cargo.lock
Cargo.toml
crates/client/Cargo.toml
crates/client/src/lib.rs
crates/client/src/repo.rs
crates/client/src/tag.rs
crates/client/src/tree.rs
tests/mod.rs

Initial client library implementation. Closes #98 .
There's still work to be done, but this something we can already start building on top of and use for testing.

feat(client): add client library crate

---

crates/app/src/repos.rs
crates/app/src/tags.rs
crates/app/src/trees.rs
crates/client/src/repo.rs
crates/client/src/tree.rs
crates/type/src/meta.rs

- Make request Content-Length mandatory (which is set by most clients anyway)
- Make request Content-Digest optional
- Closes https://github.com/profianinc/drawbridge/issues/96. If the content length header contains value:
- greater than body length => the server will block until full contents are received
- less than body length => the server will only read content length bytes, content digest should be provided to ensure integrity in this case
Refs #102 - `Content-Length` is already computed by default

feat: merge `{Request,}Meta`, validate tree leaf node lengths

---

Cargo.lock
crates/client/Cargo.toml
crates/client/src/lib.rs
crates/client/src/repo.rs
crates/client/src/tag.rs
crates/client/src/tree.rs

`enarx` client needs errors that that are `Send` and `Sync` and we need consistent error handling functionality anyway

feat(client): rely on anyhow for error handling

---

Cargo.lock
crates/client/Cargo.toml
crates/client/src/lib.rs
crates/client/src/repo.rs
crates/client/src/tag.rs
crates/client/src/tree.rs
tests/mod.rs

`reqwest::blocking` client builder attempts to `clone()`, which does not
work within Enarx keeps, migrate to simpler ureq, which works.
Blocked by #113

feat(client): migrate to `ureq`

---

.github/CODEOWNERS

Created a new @profianinc/drawbridge team, to which I added @rjzak @npmccallum @definitelynobody and myself. The team should review all Rust code in the repository. @haraldh and @bstrie can review everything else.
For Rust code in user-facing client and type crates added @bstrie as a code owner as well.

chore: rework CODEOWNERS assignments

---

.github/workflows/test.yml

The integration tests are currently broken, this PR should be reverted once the issue is fixed.
Refs #124

ci: disable auth integration tests

---

Cargo.lock
Cargo.toml
crates/app/src/trees/mod.rs
crates/client/src/tree.rs
crates/type/src/digest/digests.rs
crates/type/src/tree/path.rs

- Remove `http` crate patch. We should choose a shared location where the definition of the header should live and use for #102. Maybe just duplicate definition (as a string) in client is fine.
- Allow `.` in tree node names
- Remove duplicate copyright header

fix: various fixes for release

---

.github/CODEOWNERS

We might need some help with reviews in the repo, so adding @bstrie as CODEOWNER on the whole codebase, rather than just the user-facing crates.

ci: add @bstrie to repo-wide CODEOWNERS

---

crates/type/Cargo.toml
crates/type/src/digest/algorithms.rs
crates/type/src/digest/digests.rs

The string conversion is not isomorphic - there is a bug in the implementation. cc @rjzak 
Closes #131

fix(digest): ensure isomorphism of string conversion

---

crates/type/src/tag/context.rs

I was experiencing a compiler crash when working on this and did not see a type error reported by @bstrie (thanks!).
Quickfix to move over to other things, but we really should change the `Err` type to something better than `&'static str`, maybe we should just use `anyhow::Error` or `Box<dyn Error>`, but that's for a separate issue and PR.

fix(types): impl `FromStr` for `Tag`

---

crates/client/src/lib.rs
tests/mod.rs

There are no implementations of Into/From for URLs, and constructing them from strings is fallible anyway, so we can remove this to improve type inference.

refactor: replace Into<Url> with Url

---

crates/app/src/store/repo.rs
crates/app/src/tags/query.rs

`store` module may cache and/or store the value directly as JSON, therefore such functionality belongs there and not on the API level.

refactor(app): move tag list hash computation logic into store

---

crates/app/src/trees/get.rs
tests/mod.rs

Only allow to fetch a tree to clients that have presented a certificate signed by a CA Drawbridge is aware of (normally, Steward).
Tests should still be updated. Refs #186 
Preferably #186 should be done before this PR
With server running as:
```
RUST_LOG=trace cargo run -- --ca testdata/ca.crt --cert testdata/server.crt --key testdata/server.key --store $(mktemp -d)
```
Test via:
```
curl -vv --cacert testdata/ca.crt --cert testdata/client.crt --key testdata/client.key https://localhost:8080/user/repo/_tag/0.1.0/tree/test
```
and
```
curl -vv --cacert testdata/ca.crt https://localhost:8080/user/repo/_tag/0.1.0/tree/test
```

feat(tree): enforce client cert auth on tree fetches

---

crates/auth/src/providers/github/mod.rs
crates/auth/src/providers/github/routes.rs
crates/auth/src/session.rs

Closes #7
Username can also be used to store email or any other printable user identifier just for displaying purposes in another provider.

feat: make github username and id available in Session

---

crates/app/src/auth/mod.rs
crates/app/src/auth/oidc.rs
crates/app/src/lib.rs
crates/app/src/repos/get.rs
crates/app/src/repos/head.rs
crates/app/src/repos/put.rs
crates/app/src/store/entity.rs
crates/app/src/store/repo.rs
crates/app/src/tags/get.rs
crates/app/src/tags/head.rs
crates/app/src/tags/put.rs
crates/app/src/tags/query.rs
crates/app/src/trees/get.rs
crates/app/src/trees/head.rs
crates/app/src/trees/put.rs
crates/app/src/users/get.rs
crates/app/src/users/head.rs
crates/app/src/users/put.rs
crates/type/src/repository/config.rs
tests/mod.rs

Closes #188 
Access to private repositories will eventually be guarded by a token(#175)

feat: introduce public repositories

---

.github/workflows/release.yml

Without this permission the Release workflow cannot create a release

ci(release): add contents:write permission

---

Cargo.lock
Cargo.toml
src/main.rs

Rather than postprocessing the output of Clap, inject the config file values by preprocessing the raw program arguments. This makes the Clap-generated help output more useful, provides better error messages, requires less code, doesn't require a TOML dependency, doesn't restrict our CLI options to forms that can be easily represented in TOML, and has direct precedence from how command-line config files are used in the Java, Python, and C# ecosystems.

refactor: improve CLI config handling

---

.github/workflows/lint.yml
flake.nix
shell.nix

nix 2.8 was released recently, which updated the flake syntax
Updated the flake to the changes, set up a default formatter and formatted relevant files

build(nix): update flake syntax

---

Cargo.lock
Cargo.toml
src/main.rs

Follow-up on #213 
Closes #193 
A few problems with existing approach:
Config file of form
```toml
ca = "testdata/ca.crt"
cert = "testdata/server.crt" 
key = "testdata/server.key" 
store = "testdata"
oidc-secret = "mysecret"
oidc-client = "myclient" 
oidc-label = "mylabel"
oidc-issuer = "myissuer"
```
fails to parse:
```
error: Found argument 'ca = "testdata/ca.crt"' which wasn't expected, or isn't valid in this context
USAGE:
drawbridge [OPTIONS] --store <STORE> --cert <CERT> --key <KEY> --ca <CA> --oidc-label <OIDC_LABEL> --oidc-issuer <OIDC_ISSUER> --oidc-client <OIDC_CLIENT>
For more information try --help
```
Same behavior with:
- `ca="testdata/ca.crt"`
- `ca "testdata/ca.crt"`
- `ca testdata/ca.crt`
The implementation expects the file to contain the actual command-line arguments in …

feat: support TOML in config

---

crates/app/src/auth/oidc.rs
crates/app/src/builder.rs

This eliminates the need for client secret
cc @definitelynobody @bstrie

feat(app): use `RequestBody` auth

---

src/main.rs

The default is already shown on `--help`

fix: remove redundant CLI argument

---

Cargo.nix
crates/type/Cargo.toml

Previously the `anyhow` crate was only enabled with the `server` feature enabled, which caused compilation failures when that feature was absent.

fix: make drawbridge-type compile with default feature set

---

Cargo.nix
crates/byte/Cargo.toml

This fixes a bug we were hitting downstream related to our use of the unstable Cargo bindeps feature.

feat(byte): use features to enable serde's alloc and std features

---

crates/client/src/entity.rs
crates/client/src/lib.rs
crates/client/src/repo.rs
crates/client/src/tag.rs
crates/client/src/tree.rs
crates/client/src/user.rs
tests/mod.rs

Client and Entities using it are now each assigned a "scope", which means that we can safely reuse the client we already have, which is designed for the "root" scope for other scopes.
This is particularly relevant in `exec-wasmtime`, where we get a URL of an unknown "scope" (it may be a URL of the tag, directory or the WASM itself).
This functionality lets us programmatically "scope" an entity after e.g. validating the MIME type. (exact process of how that works is up to the user of the crate to decide, a.k.a it's an out-of-band process from perspective of this crate)
See https://github.com/enarx/enarx/pull/2118 for an example usage

feat(client): add scope support

---

crates/client/src/lib.rs
crates/server/src/handle.rs

1. Use the lowest possible API version client-side
2. Allow versions higher than of the server itself within the same major (or minor for v0.*)

feat: add API forwards-compatibility

---

crates/client/src/entity.rs

This fixes https://github.com/enarx/enarx/issues/2087. When `ureq` is imported with `gzip` feature, `Accept-Encoding` is set, which breaks the Drawbridge client, since in that case `Content-Length` is not set. Current implementation of Drawbridge requires full response to be sent verbatim without encoding.
Regarding https://github.com/enarx/enarx/issues/2087#issuecomment-1208586008, that is out-of-scope, because there is no support for streaming in Drawbridge client, this PR is a bug fix. Streaming/chunked transfer feature will be implemented as part of https://github.com/profianinc/drawbridge/issues/255

fix(client): disable response encoding

---

crates/type/src/tree/name.rs
crates/type/src/tree/path.rs

These types are used (temporarily, until they are moved) in Enarx for VFS implementation.
A few improvements that make that possible

feat(type): make `TreeName` and `TreePath` more useful

---

.github/workflows/release.yml

This creates a manifest of the OCI images, and pushes this to GitHub Packages.

build: push containers to GitHub Packages

---

crates/client/src/lib.rs
crates/server/src/auth/tls.rs

We should not hardcode specific ciphers and protocols, but just accept the defaults.
This makes sure that when better ciphers come around, we automatically get them.

chore: do not hardcode ciphers

---

crates/server/src/auth/oidc.rs
crates/server/src/builder.rs
crates/server/src/store/entity.rs
crates/server/src/store/mod.rs
crates/server/src/users/put.rs
tests/mod.rs

Remove the symlink from the oidc/ folder that points to the registered username.
This does result in allowing a single OIDC user to create multiple Drawbridge users.
Fixes: #298

feat: remove oidc symlinks

---

Cargo.lock
Cargo.toml
crates/server/Cargo.toml
crates/server/src/auth/mod.rs
crates/server/src/auth/oidc.rs
crates/server/src/builder.rs
crates/server/src/lib.rs
crates/server/src/repos/get.rs
crates/server/src/repos/head.rs
crates/server/src/repos/put.rs
crates/server/src/tags/put.rs
crates/server/src/trees/put.rs
crates/server/src/users/get.rs
crates/server/src/users/head.rs
crates/server/src/users/put.rs
flake.nix
src/main.rs
tests/mod.rs

Change verification of Access Token to actually verify JWT signatures and audience/scope claims.
This prevents tokens issued for one service or environment to be used here, and for tokens acquired for limited permissions to be used for others.
It also means no network requests need to be performed during verification of requests.

feat: check access token

---

src/main.rs

This was put in place during the move to async-std, and limits the number of active connections to 1.
Fixes: d445a946

fix: remove limit of 1 active connection

---

flake.nix

Extracted from https://github.com/profianinc/nixpkgs/blob/650d0afe6fc8b961896ce8b63aebbbc0c7ed2cee/nixos/modules/services/networking/drawbridge.nix This has been tested on multiple infrastructures already

build(nix): add Drawbridge NixOS module

---

Cargo.lock
Cargo.toml
crates/byte/src/lib.rs
crates/server/src/auth/oidc.rs
crates/server/src/builder.rs
crates/server/src/lib.rs
crates/server/src/store/entity.rs
crates/type/src/digest/digests.rs
src/main.rs
tests/mod.rs

Some errors in the output which somehow still allowed the unit test to pass successfully, not sure if intentional or not.
```
Running tests/mod.rs (target/debug/deps/mod-839111660b709219)
running 1 test
test app ... 2023-02-01T03:28:29.146903Z ERROR app::auth::oidc: failed to verify token error=Error decoding token
Caused by:
ExpiredSignature
2023-02-01T03:28:29.151279Z ERROR app::auth::oidc: failed to verify token error=Error decoding token
Caused by:
InvalidAudience
2023-02-01T03:28:29.159868Z ERROR app::auth::oidc: failed to verify token error=Error decoding token
Caused by:
InvalidIssuer
2023-02-01T03:28:29.163667Z ERROR app::auth::oidc: failed to verify token error=Error decoding token
Caused by:
Base64 error: Encoded text cannot have a 6-bit remainder.
ok
```
The Base64 error …

chore: update some dependences, fix some clippy errors

---

crates/server/src/builder.rs

It seems that Rust 1.71 introduced a new pattern for Clippy where a struct that derives `Default` can just use `StructName` instead of `StructName::default()`.
Related to https://github.com/profianinc/steward/pull/276

fix: clippy issue resolved

---

Cargo.lock
Cargo.toml
crates/client/src/lib.rs
tests/mod.rs

`webpki-roots` had a breaking change, updated other dependencies; also ran `cargo update`
`axum` needs to be updated to `0.6`, but that will take more time to figure out.

chore: update dependencies
